# Generated by Django 5.1.2 on 2024-10-20 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, default='uncategorized', unique=True),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
